# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Portillo
email: portillo.david1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  David Portillo tenor, singer, artist specializing in the Opera.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.davidportillotenor.com/" # the base hostname & protocol for your site

# URIs and links
permalink: /:categories/:title

links:
  - title: BIOGRAPHY
    url: /biography
  - title: ACCLAIMS
    url: /acclaims
  - title: CALENDAR
    url: /calendar
  - title: MEDIA
    url: /media

# Social Media
twitter_username: elportillo
facebook_username:  davidportillotenor
linkedin_username: david.portillo
instagram_username: porttenor

# sass Options
sass:
    style: :compressed
# Build settings
markdown: kramdown
